### ISSUE TITLE
Gini for continuous response

### ISSUE THREAD

**Issue by spedygiorgio** [JackStat/ModelMetrics#15]
I see that the package implements Gini for binary response. Nevertheless in many application it could be used also when the response is not negative (insurance losses for example). A five - year old code found in Kaggle is this: 

```
normalizedGini <- function(aa, pp) {
  .Gini <- function(a, p) {
    if (length(a) !=  length(p)) stop("Actual and Predicted need to be equal lengths!")
    temp.df <- data.frame(actual = a, pred = p, range=c(1:length(a)))
    temp.df <- temp.df[order(-temp.df$pred, temp.df$range),]
    population.delta <- 1 / length(a)
    total.losses <- sum(a)
    null.losses <- rep(population.delta, length(a)) # Hopefully is similar to accumulatedPopulationPercentageSum
    accum.losses <- temp.df$actual / total.losses   # Hopefully is similar to accumulatedLossPercentageSum
    gini.sum <- cumsum(accum.losses - null.losses)  # Not sure if this is having the same effect or not
    sum(gini.sum) / length(a)
  }
  .Gini(aa,pp) / .Gini(aa,aa)
}
```

Would be possible to enrich the function available in the package with with feature? Best

**Comment by JackStat** [comment]
Thanks for the issue.

**Comment by spedygiorgio** [comment]
Hope to se it in the next release!

**Comment by spedygiorgio** [comment]
Thank you again for your great package!

**Comment by spedygiorgio** [comment]
I was trying to use the function but I receive this error:

out<-with(db4scoring, ModelMetrics::gini(actual=numero, predicted = numeroPred))
Error in binaryChecks(actual, "auc") : 
  auc only works for binary outcomes at this time
