### ISSUE TITLE
Failed installation with install.packages('ModelMetrics')

### ISSUE THREAD

**Issue by FlorianDr** [JackStat/ModelMetrics#24]
I'm trying to use `caret` and `ModelMetrics`.  Both installation options fail with: 
```shell
auc_.cpp:2:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [auc_.o] Error 1
ERROR: compilation failed for package 'ModelMetrics'
* removing '/usr/local/lib/R/3.5/site-library/ModelMetrics'
Installation failed: Command failed (1)
```
I'm on OS X and R Studio 1.1.456

**Comment by JackStat** [comment]
Apple kind of messed things up for openmp by forcing creating a symlink called clang to gcc... and broke some functionality. This stackoverflow has more information. If you get the proper version it will work. In the mean time I may need to rewrite without openmp.

https://stackoverflow.com/questions/25990296/how-to-include-omp-h-in-os-x

**Comment by ifernandolopez** [comment]
See how I solved it here:
https://stackoverflow.com/a/52871786/160829

**Comment by twitched** [comment]
`brew install libomp`, mentioned at https://stackoverflow.com/a/52871786/160829 seems to work if you use brew.

**Comment by JackStat** [comment]
omp seems to be becoming a problem. If anyone has any ideas on a replacement let me know

**Comment by swvanderlaan** [comment]
> `brew install libomp`, mentioned at https://stackoverflow.com/a/52871786/160829 seems to work if you use brew.

That was an awesome tip!

**Comment by rstub** [comment]
> omp seems to be becoming a problem. If anyone has any ideas on a replacement let me know

Have you tried `RcppParallel`?

BTW, from my reading of [WRE](https://cran.rstudio.com/doc/manuals/r-release/R-exts.html#OpenMP-support) I would think you have to add suitable compiler flags to enable OpenMP.

**Comment by karoliskoncevicius** [comment]
For people using MacPorts instead of homebrew - use +top_level variant to add "omp.h" to /libs/

    sudo port install libomp +top_level
